export const southAfricaSuburbs: { label: string; value: string }[] = [
  { label: "Addo", value: "Addo" },
  { label: "Alberton", value: "Alberton" },
  { label: "Ballito", value: "Ballito" },
  { label: "Barberton", value: "Barberton" },
  { label: "Bedfordview", value: "Bedfordview" },
  { label: "Bela Bela", value: "Bela Bela" },
  { label: "Bellville", value: "Bellville" },
  { label: "Bergvliet", value: "Bergvliet" },
  { label: "Bethlehem", value: "Bethlehem" },
  { label: "Bhisho", value: "Bhisho" },
  { label: "Bloemfontein", value: "Bloemfontein" },
  { label: "Boksburg", value: "Boksburg" },
  { label: "Burgundy Estate", value: "Burgundy Estate" },
  { label: "Burgersdorp", value: "Burgersdorp" },
  { label: "Cape Town", value: "Cape Town" },
  { label: "Centurion", value: "Centurion" },
  { label: "Ceres", value: "Ceres" },
  { label: "Claremont", value: "Claremont" },
  { label: "Colesberg", value: "Colesberg" },
  { label: "Constantia", value: "Constantia" },
  { label: "De Aar", value: "De Aar" },
  { label: "Durban", value: "Durban" },
  { label: "Durbanville", value: "Durbanville" },
  { label: "East London", value: "East London" },
  { label: "Ekurhuleni", value: "Ekurhuleni" },
  { label: "Empangeni", value: "Empangeni" },
  { label: "Fish Hoek", value: "Fish Hoek" },
  { label: "Gardens", value: "Gardens" },
  { label: "George", value: "George" },
  { label: "Gordon's Bay", value: "Gordon's Bay" },
  { label: "Grahamstown", value: "Grahamstown" },
  { label: "Green Point", value: "Green Point" },
  { label: "Groblersdal", value: "Groblersdal" },
  { label: "Harrismith", value: "Harrismith" },
  { label: "Howick", value: "Howick" },
  { label: "Hout Bay", value: "Hout Bay" },
  { label: "Jeffreys Bay", value: "Jeffreys Bay" },
  { label: "Johannesburg", value: "Johannesburg" },
  { label: "Kalk Bay", value: "Kalk Bay" },
  { label: "Kenilworth", value: "Kenilworth" },
  { label: "Kimberley", value: "Kimberley" },
  { label: "King Williams Town", value: "King Williams Town" },
  { label: "Klerksdorp", value: "Klerksdorp" },
  { label: "Knysna", value: "Knysna" },
  { label: "Komatipoort", value: "Komatipoort" },
  { label: "KwaMashu", value: "KwaMashu" },
  { label: "Lephalale", value: "Lephalale" },
  { label: "Lichtenburg", value: "Lichtenburg" },
  { label: "Lydenburg", value: "Lydenburg" },
  { label: "Mahikeng", value: "Mahikeng" },
  { label: "Makhado", value: "Makhado" },
  { label: "Macassar", value: "Macassar" },
  { label: "Melkbosstrand", value: "Melkbosstrand" },
  { label: "Meyerton", value: "Meyerton" },
  { label: "Midrand", value: "Midrand" },
  { label: "Modimolle", value: "Modimolle" },
  { label: "Mowbray", value: "Mowbray" },
  { label: "Mthatha", value: "Mthatha" },
  { label: "Mthunzini", value: "Mthunzini" },
  { label: "Muizenberg", value: "Muizenberg" },
  { label: "Nelspruit", value: "Nelspruit" },
  { label: "Newcastle", value: "Newcastle" },
  { label: "Observatory", value: "Observatory" },
  { label: "Parys", value: "Parys" },
  { label: "Paternoster", value: "Paternoster" },
  { label: "Pella", value: "Pella" },
  { label: "Pietermaritzburg", value: "Pietermaritzburg" },
  { label: "Pofadder", value: "Pofadder" },
  { label: "Polokwane", value: "Polokwane" },
  { label: "Port Elizabeth", value: "Port Elizabeth" },
  { label: "Port Shepstone", value: "Port Shepstone" },
  { label: "Postmasburg", value: "Postmasburg" },
  { label: "Potchefstroom", value: "Potchefstroom" },
  { label: "Pretoria", value: "Pretoria" },
  { label: "Randburg", value: "Randburg" },
  { label: "Richards Bay", value: "Richards Bay" },
  { label: "Rondebosch", value: "Rondebosch" },
  { label: "Roodepoort", value: "Roodepoort" },
  { label: "Rustenburg", value: "Rustenburg" },
  { label: "Sasolburg", value: "Sasolburg" },
  { label: "Sandton", value: "Sandton" },
  { label: "Sea Point", value: "Sea Point" },
  { label: "Secunda", value: "Secunda" },
  { label: "Simon's Town", value: "Simon's Town" },
  { label: "Somerset West", value: "Somerset West" },
  { label: "Soweto", value: "Soweto" },
  { label: "Springbok", value: "Springbok" },
  { label: "Stellenbosch", value: "Stellenbosch" },
  { label: "Strand", value: "Strand" },
  { label: "Thohoyandou", value: "Thohoyandou" },
  { label: "Tzaneen", value: "Tzaneen" },
  { label: "Uitenhage", value: "Uitenhage" },
  { label: "Umlazi", value: "Umlazi" },
  { label: "Upington", value: "Upington" },
  { label: "Vanderbijlpark", value: "Vanderbijlpark" },
  { label: "Welkom", value: "Welkom" },
  { label: "White River", value: "White River" },
  { label: "Witbank", value: "Witbank" },
  { label: "Wynberg", value: "Wynberg" },
  { label: "Zeerust", value: "Zeerust" },
  { label: "Other", value: "Other" },
]
